name: Deploy Lambda Function

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip and create package
        run: |
          sudo apt-get update && sudo apt-get install -y zip
          zip -r code.zip .

      - name: Update Lambda function
        uses: imhedi/actions-awscli-v2@latest
        with:
          args: >
            lambda update-function-code
            --function-name TestFunction
            --zip-file fileb://code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
